=== hlapidez/anhquan/trunk/CodeGenerator4j/src/main/schemas/ClassSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2009 http://anhquan.de

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:de:anhquan:codegen:model" xmlns:gen="urn:de:anhquan:codegen:model" elementFormDefault="qualified">

    <element name="ClassTable" type="gen:ClassTableType"></element>

    <complexType name="ClassDescriptionType">
    	<sequence>
    		<element name="Name" type="string" minOccurs="1"></element>
    		<element name="Package" type="string" minOccurs="1"></element>
    		<element name="Template" type="string" minOccurs="1"></element>
    		<element name="PrimaryKeyType" type="string" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="ClassTableType">
    	<sequence>
    		<element name="ClassDescriptions" type="gen:ClassDescriptionType"
    			minOccurs="1" maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="TargetDirectory" type="string" use="required"></attribute>
    	<attribute name="License" type="string" use="required"></attribute>
    	<attribute name="Author" type="string" use="required"></attribute>
    </complexType>
</schema>

=== hlapidez/anhquan/CodeGenerator4j/src/main/models/DemoClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2009 http://anhquan.de

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<gen:ClassTable Author="Anh Quan Nguyen" License="Apache License Version 2.0" TargetDirectory="src/main/java" xmlns:gen="urn:de:anhquan:codegen:model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:de:anhquan:codegen:model ../schemas/ClassSchema.xsd ">
  <gen:ClassDescriptions>
    <gen:Name>ImageBlobDao</gen:Name>
    <gen:Package>de.anhquan.demo</gen:Package>
    <gen:Template>src/main/templates/HelloWorld.class.tpl</gen:Template>
    <gen:PrimaryKeyType>Integer</gen:PrimaryKeyType>
  </gen:ClassDescriptions>
  <gen:ClassDescriptions>
  	<gen:Name>GoodBye</gen:Name>
  	<gen:Package>de.anhquan.demo</gen:Package>
  	<gen:Template>src/main/templates/GoodBye.class.tpl</gen:Template>
    <gen:PrimaryKeyType>Integer</gen:PrimaryKeyType>
  </gen:ClassDescriptions>
</gen:ClassTable>
